#!/usr/bin/env bash
# PreToolUse (Edit|Write): deny hand edits to files a tool generates. Editing
# them by hand is lost on the next run and hides the real fix.
#
#   .react-router/   route types from `react-router typegen` (bun run typecheck)
#   build/           production build output (bun run build)
#   coverage/        coverage reports (bun run coverage)
#   bun.lock         bun's lockfile (bun add / bun remove / bun install)
#
# Self-contained on purpose: it works whether or not the agent-ops hooks are
# present. Needs jq; without it, it drains stdin and exits 0.
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  cat >/dev/null 2>&1 || true
  exit 0
fi

input=$(cat)
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[ -z "$file_path" ] && exit 0

root=${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}
root=${root%/}
# The root as given and, when it exists, with symlinks resolved (/tmp vs /private/tmp), so a
# trailing slash or a symlinked path can't route a generated file around the guard.
phys=$(cd "${root:-/}" 2>/dev/null && pwd -P) || phys=$root
phys=${phys%/}
case "$file_path" in
"$root"/*) rel=${file_path#"$root"/} ;;
"$phys"/*) rel=${file_path#"$phys"/} ;;
/*) exit 0 ;;
*) rel=$file_path ;;
esac

reason=""
case "$rel" in
.react-router/*) reason="$rel is generated by react-router typegen. Change the route module or app/routes.ts, then run bun run typecheck." ;;
build/*) reason="$rel is build output. Change the source and run bun run build." ;;
coverage/*) reason="$rel is a coverage report. Run bun run coverage to regenerate it." ;;
bun.lock) reason="bun.lock is written by bun. Change package.json with bun add / bun remove, or run bun install." ;;
esac
[ -z "$reason" ] && exit 0

jq -n --arg r "BLOCKED: $reason" \
  '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $r}}'
